Add LeaderScheduleEntry
deso-protocol/postgres-data-handler pull request #12
Opened 2024-02-15 23:25 UTC by lazynina

2024-02-15 23:26 UTC, lazynina commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/deso-protocol/postgres-data-handler/12?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #4** <a href="https://app.graphite.dev/github/pr/deso-protocol/postgres-data-handler/4?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #5** <a href="https://app.graphite.dev/github/pr/deso-protocol/postgres-data-handler/5?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #9** <a href="https://app.graphite.dev/github/pr/deso-protocol/postgres-data-handler/9?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12** <a href="https://app.graphite.dev/github/pr/deso-protocol/postgres-data-handler/12?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/postgres-data-handler/12?utm_source=stack-comment).

2024-02-16 20:32 UTC, superzordon requested changes
A few small refactors for code understandability and cleanliness, but otherwise looks good to me!

2024-02-16 20:32 UTC, superzordon commented on entries/epoch.go
> +	if epochEntry.EpochNumber >= 2 {
Can you add a comment explaining this?

2024-02-16 20:32 UTC, superzordon commented on entries/pkid.go
> +	glog.Infof("PkidBatchOperation: Putting %d entries into the database", len(entries))
Lets remove this before merging, or if it's necessary for debugging in a deployed environment, just throw a FIXME above it to remove.

2024-02-16 20:32 UTC, superzordon commented on entries/pkid.go
> +	// NOTE: if we need to support parsing other indexes for PKIDs beyond LeaderSchedule,
Just for the sake of completeness, lets do a prefix filter on the uniqueEntries to just the leader schedule prefix, and use that slice in the rest of the function.

2024-02-16 21:00 UTC, superzordon approved these changes

2024-02-16 21:04 UTC, merged